"use client";
import { create } from "zustand";
import { db, today, type Attendance, type Expense, type ExpenseCategory, type Project, type Worker, type WorkerPayment } from "@/lib/db";
type ProjectInput = Omit<Project, "id" | "status" | "createdAt">; type ExpenseInput = Omit<Expense, "id" | "date">; type WorkerInput = Omit<Worker, "id" | "status">;
interface AppState { projects: Project[]; expenses: Expense[]; workers: Worker[]; attendance: Attendance[]; payments: WorkerPayment[]; loading: boolean; fetchAll: () => Promise<void>; addProject: (input: ProjectInput) => Promise<number>; addExpense: (input: ExpenseInput) => Promise<void>; addWorker: (input: WorkerInput) => Promise<void>; finishProject: (id: number) => Promise<void>; checkInWorker: (workerId: number, projectId: number, multiplier: Attendance["multiplier"], date?: string) => Promise<void>; checkOutWorker: (attendanceId: number) => Promise<void>; editAttendance: (attendanceId: number, multiplier: Attendance["multiplier"], status: Attendance["status"]) => Promise<void>; addPayment: (workerId: number, amount: number, note: string) => Promise<void>; }
export const useAppStore = create<AppState>((set, get) => ({ projects: [], expenses: [], workers: [], attendance: [], payments: [], loading: true,
 fetchAll: async () => { const [projects, expenses, workers, attendance, payments] = await Promise.all([db.projects.reverse().sortBy("createdAt"), db.expenses.reverse().sortBy("date"), db.workers.toArray(), db.attendance.reverse().sortBy("date"), db.payments.reverse().sortBy("date")]); set({ projects, expenses, workers, attendance, payments, loading: false }); },
 addProject: async (input) => { const id = await db.projects.add({ ...input, status: "active", createdAt: new Date().toISOString() }); await get().fetchAll(); return id as number; },
 addExpense: async (input) => { await db.expenses.add({ ...input, date: today() }); await get().fetchAll(); }, addWorker: async (input) => { await db.workers.add({ ...input, status: "active" }); await get().fetchAll(); },
 finishProject: async (id) => { await db.projects.update(id, { status: "finished", finishedAt: new Date().toISOString() }); await get().fetchAll(); },
 checkInWorker: async (workerId, projectId, multiplier, selectedDate) => { const date = selectedDate || today(); const existing = await db.attendance.where("[workerId+projectId+date]").equals([workerId, projectId, date]).first(); if (existing) await db.attendance.update(existing.id!, { multiplier, status: "arrived", checkedInAt: new Date().toISOString(), checkedOutAt: undefined }); else await db.attendance.add({ workerId, projectId, date, multiplier, status: "arrived", checkedInAt: new Date().toISOString() }); await get().fetchAll(); },
 checkOutWorker: async (attendanceId) => { await db.attendance.update(attendanceId, { status: "left", checkedOutAt: new Date().toISOString() }); await get().fetchAll(); },
 editAttendance: async (attendanceId, multiplier, status) => { await db.attendance.update(attendanceId, { multiplier, status, checkedOutAt: status === "left" ? new Date().toISOString() : undefined }); await get().fetchAll(); },
 addPayment: async (workerId, amount, note) => { await db.payments.add({ workerId, amount, note, date: today(), createdAt: new Date().toISOString() }); await get().fetchAll(); }, }));
export const expenseCategories: ExpenseCategory[] = ["Material", "Transport", "Workers", "Other"];
